# -*- coding: utf-8 -*-
"""spam_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydqOQ7VvDsYNlKW8wix2YX59-Rg9rbDG
"""

import numpy as np
import pandas as pd

# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "spam.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "uciml/sms-spam-collection-dataset",
  file_path,
  pandas_kwargs={'encoding': 'latin-1'}
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

df.head()

df.shape

df.info()

df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace=True)

df.head()

from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['v1']=encoder.fit_transform(df['v1'])

df.head()

df=df.drop_duplicates(keep='first').copy()

df.duplicated().sum()

df.shape

import nltk

df['chars']=df['v2'].apply(len)


nltk.download('punkt_tab')

df['nw']=df['v2'].apply(lambda x:len(nltk.word_tokenize(x)))



df['ns']=df['v2'].apply(lambda x:len(nltk.sent_tokenize(x)))

df.head()

df.describe()

import seaborn as sns

sns.histplot(df[df['v1']==0]['chars'])
sns.histplot(df[df['v1']==1]['chars'],color='red')

sns.histplot(df[df['v1']==0]['nw'])
sns.histplot(df[df['v1']==1]['nw'],color='red')

sns.histplot(df[df['v1']==0]['ns'])
sns.histplot(df[df['v1']==1]['ns'],color='red')

sns.heatmap(df.drop('v2', axis=1).corr(), annot=True)

def tt(v2):
  v2=v2.lower()
  v2 = nltk.word_tokenize(v2)
  y=[]
  for i in v2:
    if i.isalnum():
      y.append(i)
  v2=y[:]
  y.clear()
  for i in v2:
    if i not in stopwords.words('english') and i not in string.punctuation:
      y.append(i)
  v2=y[:]
  y.clear()
  for i in v2:
    y.append(ps.stem(i))
  return " ".join(y)

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords.words('english')

import string
string.punctuation

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

df['v2'][0]

tt('Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...')

df['v2'].apply(tt)

df['tt']=df['v2'].apply(tt)

df.head()

from wordcloud import WordCloud
wc=WordCloud(width=500,height=500,min_font_size=10,background_color='white')

swc=wc.generate(df[df['v1']==1]['tt'].str.cat(sep=" "))

import matplotlib.pyplot as plt
plt.figure(figsize=(15,6))
plt.imshow(swc)

hwc=wc.generate(df[df['v1']==0]['tt'].str.cat(sep=" "))
plt.figure(figsize=(15,6))
plt.imshow(hwc)

spc=[]
for i in df[df['v1']==1]['tt'].tolist():
  for j in i.split():
    spc.append(j)

from collections import Counter
pd.DataFrame(Counter(spc).most_common(30))

from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv=CountVectorizer()
tfidf=TfidfVectorizer()

X=tfidf.fit_transform(df['tt']).toarray()

X.shape

y=df['v1'].values

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

gnb=GaussianNB()
mnb=MultinomialNB()
bnb=BernoulliNB()

gnb.fit(X_train,y_train)
y_pred=gnb.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(precision_score(y_test,y_pred))

mnb.fit(X_train,y_train)
y_pred2=mnb.predict(X_test)
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(precision_score(y_test,y_pred2))

bnb.fit(X_train,y_train)
y_pred3=bnb.predict(X_test)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(precision_score(y_test,y_pred3))
